### ISSUE TITLE
README does not display properly on PyPI

### ISSUE THREAD

**Issue by lebigot** [closeio/ciso8601#10]
The README does not display properly on PyPI (https://pypi.python.org/pypi/ciso8601/1.0.1). The unfortunate result is that it does not give a good image of this otherwise very useful module.

I would guess that naming the file `README.rst` would fix this.

**Comment by thomasst** [comment]
v1.0.2 with improved README now on pypi! https://pypi.python.org/pypi/ciso8601/

Sorry this took so long.
