### ISSUE TITLE
Support for Python >= 3.9

### ISSUE THREAD

**Issue by DefauIt** [closeio/ciso8601#103]
pls, add support for python version >= 3.9.

**Comment by movermeyer** [comment]
FWIW, AFAIK, `ciso8601` works fine on Python 3.9+ already.

I agree that there should be a release so the metadata is updated, but we haven't heard of any problems running it on 3.9+.

Are you seeing any issues?

**Comment by DefauIt** [comment]
Opps, sorry....
it was my mistake, misspelled in ebuild.
