### ISSUE TITLE
String 1985-04-12T23:20:50,52Z fails with parse_rfc3339

### ISSUE THREAD

**Issue by philvarner** [closeio/ciso8601#110]
This fails with the error "UTC offset is mandatory in RFC 3339 format.":
```
ciso8601.parse_rfc3339("1985-04-12T23:20:50,52Z")
```

I believe the problem is use of the `,` as the secs/ms separator, as using a `.` works. 

Per the spec, either is allowed (https://datatracker.ietf.org/doc/html/rfc3339)

```
   time-fraction     = ("," / ".") 1*DIGIT
```

I believe the fix is, in `module.c` to change:

```
#define IS_FRACTIONAL_SEPARATOR (*c == '.' || (*c == ',' && !rfc3339_only))
```

to

```
#define IS_FRACTIONAL_SEPARATOR (*c == '.' || (*c == ','))
```

**Comment by movermeyer** [comment]
Interesting....three years ago I was under the impression that commas were not allowed: https://github.com/closeio/ciso8601/pull/70/commits/73ae06712545c2b9654e1a2be9271b1b4fb019ad 

I wonder how I messed that up 🤔

**Comment by philvarner** [comment]
Uuuuugh, I didn't notice that the grammar was for ISO 8601 and not RFC 3339. Sorry for the misdirection, and thanks for correcting it!

**Comment by movermeyer** [comment]
No worries! Glad whenever something turns out to be "not a bug". 😁
