### ISSUE TITLE
Manylinux arm wheel

### ISSUE THREAD

**Issue by StefanFabian** [closeio/ciso8601#117]
Thanks a lot for this great project!
I'm using some functions of this in an AWS lambda layer.
This worked fine so far, however, now that they have arm64 cores, I've tried switching to arm64 and noticed that it can not import `'parse_datetime' from 'ciso8601' (unknown location)`.
I've noticed that there doesn't seem to be an arm wheel for this package except for one for macOS.
I don't know how much work it would be to add a wheel for arm64 but I just wanted to say that there is demand if it isn't too much work.
For now, I will just switch back to x86 since it is currently just a private project and the cost difference doesn't matter.

**Comment by movermeyer** [comment]
v2.3.0 was just released with pre-built wheels for many platforms. 🎉 

Give it a shot and let us know if you see any issues.
