### ISSUE TITLE
Parsing bad date strings crashes pypy interpreter

### ISSUE THREAD

**Issue by bcattle** [closeio/ciso8601#12]
Nice job on the library guys. I'm not sure if this is an issue with pypy or with the library. If you pass in a bad string, this library crashes the interpreter entirely:

    $ pypy
    Python 2.7.9 (295ee98b69288471b0fcf2e0ede82ce5209eb90b, Jun 02 2015, 18:26:45)
    [PyPy 2.6.0 with GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>>> import ciso8601
    >>>> ciso8601.parse_datetime_unaware('not-a-date')
    pypy(36682,0x7fff7b7db300) malloc: *** error for object 0x1016df220: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

FWIW normal python 2.7.10 doesn't have the same problem:

    $ python
    Python 2.7.10 (default, Jul 22 2015, 21:18:21) 
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ciso8601
    >>> ciso8601.parse_datetime_unaware('not-a-date')
    >>> 

Thanks

**Comment by thomasst** [comment]
In this case it should return `Py_RETURN_NONE` right away (we can't parse the year), so I'm not sure why this would crash pypy. Is this a stable build of pypy? Does replacing it with `Py_BuildValue("");` work?

**Comment by jesper** [comment]
Experiencing this issue with v1.0.1 on PyPy 5.0.1 on Ubuntu Linux.

`
>>>> import ciso8601
>>>> ciso8601.parse_datetime("herp derp")
RPython traceback:
  File "pypy_interpreter.c", line 37804, in BuiltinCodePassThroughArguments1_funcrun_obj
  File "pypy_module_cpyext_5.c", line 23741, in generic_cpy_call__StdObjSpaceConst_funcPtr_SomeI
Fatal RPython error: AssertionError
[1]    613 abort (core dumped)  pypy
`

**Comment by jesper** [comment]
FWIW, this seems to be fixed in master. I reckon a release would make very many pypy users happy :)

**Comment by thomasst** [comment]
Good point, will take a look at this and create a new release. Thanks for letting me know!

**Comment by thomasst** [comment]
v1.0.2 now on pypi! https://pypi.python.org/pypi/ciso8601/

Sorry this took so long.
