### ISSUE TITLE
The optimization of speeding up

### ISSUE THREAD

**Issue by qidanrui** [closeio/ciso8601#124]
Hi @movermeyer , great project!
I'm little curious about why your implementation is faster than pendulum? What optimization have you used?

**Comment by movermeyer** [comment]
Disclaimers:

* I haven't looked at the `pendulum` code in some time, so I might be forgetting things
* Unlike `pendulum`, `ciso8601` implements only the [most common subset](https://github.com/closeio/ciso8601#supported-subset-of-iso-8601) of the ISO 8601 spec. This allows the code to be simpler.

For a long time, `ciso8601` was comparable to, but slightly slower than, `pendulum` when it came to parsing timestamps that contained timezones. Then we copied their idea of creating a barebones [`FixedOffset` timezone object](https://github.com/closeio/ciso8601/pull/58). It gave `ciso8601` the performance edge over `pendulum`.

These `FixedOffset` are much more lightweight (in both memory size and code complexity) than the Python 3.7 `[datetime.timezone](https://docs.python.org/3/library/datetime.html#timezone-objects)` and even more so when compared against the `pytz` objects `ciso8601` was using for Python 2.7 compatibility.

We also started [caching the timezone objects](https://github.com/closeio/ciso8601/pull/102). This doesn't help the single-parse benchmarks you see in the README (where we disable caching), but it does speed things up considerably in real-world usage.

You can dig more into the performance improvements by checking out the [`performance` tag](https://github.com/closeio/ciso8601/issues?q=label%3Aperformance)

**Comment by movermeyer** [comment]
Closing this as answered.

Going forward, new performance related PRs will continue to get the [`performance` label](https://github.com/closeio/ciso8601/issues?q=label%3Aperformance) added to them.
