### ISSUE TITLE
Please provide wheels on PyPI

### ISSUE THREAD

**Issue by mckelvin** [closeio/ciso8601#25]
Hi there, I Googled `python+dateutil+parse+slow` and find the `ciso8601`. Thanks for developing the amazing library. Please consider provide [wheels](http://pythonwheels.com/) on [PyPI](https://pypi.python.org/pypi/ciso8601) to make it easier to install.

**Comment by thomasst** [comment]
I haven't used wheels before but it appears that they'd have to be compiled for each platform. What's the easiest way to build wheels for all popular platforms with each release?

**Comment by mckelvin** [comment]
I don't think there's an easy way to cross compile for all popular platforms but a wheel package for Linux is fair enough.

**Comment by dahlia** [comment]
The easiest way I've tried is using Travis CI's `linux`/`osx` matrix with AppVeyor.  With these services (that are all free for an open source project) we can build wheels for 3 major platforms (Linux, macOS, Windows) for every build in the automated way.

**Comment by 2xyo** [comment]
This PR has been refused due to the absence of wheels https://github.com/oasis-open/cti-python-stix2/pull/386 

> [...] However, I would rather not introduce a dependency that requires compiling C code to install, and ciso8601 doesn't provide pre-compiled wheels. [...]

**Comment by davinchia** [comment]
Hi, is there any update here? We are suddenly running into this issue and I notice this has been open for a couple of years now.

**Comment by kylebarron** [comment]
FYI just came across this repo and this issue; I added an example of using CI to build wheels across many platforms in https://github.com/closeio/ciso8601/pull/109

**Comment by danielloader** [comment]
Thanks for the PR @kylebarron, it'd be nice to get wheels because I'm currently trying to use containers with lambda and it's forcing installing the whole C build chain in the build process (it's not critical but it's time and time is money).

**Comment by xuefer** [comment]
···
Building wheels for collected packages: ciso8601
  Building wheel for ciso8601 (pyproject.toml) ... error
  ERROR: Failed building wheel for ciso8601
Failed to build ciso8601
ERROR: Could not build wheels for ciso8601, which is required to install pyproject.toml-based projects
···

+1 on providing whl prebuilts

**Comment by rouge8** [comment]
Now that #109 is merged, any chance of uploading wheels for 2.2.0?

**Comment by garrettheel** [comment]
@movermeyer bumping this one again. looks like all the infra is in place to publish wheels, would it be possible to push them up for 2.2.0 and for future versions? happy to contribute if there's something missing

**Comment by kylebarron** [comment]
Gentle nudge for a new release 🙂. It's been 10 months since my PR to add wheel building to CI was merged, but it appears that a new release was never made. Even a patch release that just adds wheels would be super helpful for downstream projects.

**Comment by movermeyer** [comment]
v2.3.0 was just released with pre-built wheels for many platforms. 🎉
