### ISSUE TITLE
Bad date causes crash 

### ISSUE THREAD

**Issue by batkuip** [closeio/ciso8601#35]
```
        dt = '2017-0012-27T13:35:19+0200'
        boom = ciso8601.parse_datetime(dt)
```
causes segmentation fault

**Comment by thomasst** [comment]
This crashes on v1.0.5 but works fine on v1.0.6. Can you confirm this?

**Comment by batkuip** [comment]
Yup - fixed.  My bad for not checking for an update.  Thanks for the quick response.
