### ISSUE TITLE
ciso8601 should specify and enforce a code style

### ISSUE THREAD

**Issue by movermeyer** [closeio/ciso8601#40]
The codebase of ciso8601 is a mix of various C coding/formatting styles.

The classic example in C is where opening `{` should go. In ciso8601, we have examples of both:

* [Same line](https://github.com/closeio/ciso8601/blob/e886109dc8f6a7168a1d4d38ca3b48ef26a03610/module.c#L187)
* [Next line](https://github.com/closeio/ciso8601/blob/e886109dc8f6a7168a1d4d38ca3b48ef26a03610/module.c#L145)

`ciso8601` should specify a C formatting style and enforce it. 
This could then be put into a [`.clang-format` file](https://clang.llvm.org/docs/ClangFormatStyleOptions.html), so that developer's IDE's could enforce the style as they code.

While I don't care which format is chosen, I do want ciso8601 to have a consistent style and for my contributions to match that style.

**Comment by thomasst** [comment]
Let's use the PEP7 style.
