### ISSUE TITLE
Draft a CONTRIBUTING.md

### ISSUE THREAD

**Issue by movermeyer** [closeio/ciso8601#49]
When I joined the project, there were a bunch of process things I had to learn.

I would like to create a `CONTRIBUTING.md` file, that would document the goals of the project, the tooling, and the process for contributing  (see [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) for a complicated example).

**Comment by thomasst** [comment]
Done in https://github.com/closeio/ciso8601/commit/1b7befabf59058157f7424272d1ba689b8782499
