### ISSUE TITLE
Update benchmarks in README

### ISSUE THREAD

**Issue by thomasst** [closeio/ciso8601#53]
Should ideally have a breakdown for the latest stable Python versions (2.7, 3.6), and for 3.7.

**Comment by movermeyer** [comment]
And also include new methods:

* [maya](https://github.com/kennethreitz/maya)
* Python 3.7's changed `%z` [`strptime` format code](https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior):

> Changed in version 3.7: When the %z directive is provided to the strptime() method, the UTC offsets can have a colon as a separator between hours, minutes and seconds. For example, '+01:00:00' will be parsed as an offset of one hour. In addition, providing 'Z' is identical to '+00:00'.

The `strptime` method is still not a full ISO 8601 parser, but we show a `strptime` example in the non-timezone information example. Now we can show one in the other example too.

There are also some other ISO 8601 libraries that we don't mention:

* [iso8601plus](https://pypi.org/project/iso8601plus/)
    * `iso8601.parse_date("2007-01-25T12:00:00Z")`

* [iso8601utils](https://pypi.org/project/iso8601utils/)
    * `parsers.datetime('2007-08-09T12:30-02:00')`

* [PySO8601](https://pypi.org/project/PySO8601/)
    * `PySO8601.parse('2011-01-01T14:32')`

* [pyiso8601](https://bitbucket.org/micktwomey/pyiso8601/src)
    * `iso8601.parse_date("2007-01-25T12:00:00Z")`

It might be worth mentioning these, for completeness.

**Comment by movermeyer** [comment]
**Install dependencies:**
`pip install ciso8601 aniso8601 iso8601 isodate python-dateutil arrow maya udatetime iso8601utils moment pyso8601 str2date`

**Test script (bash, `comparisons.sh`):**
```bash
$1 -m timeit -s 'import ciso8601' "ciso8601.parse_datetime('$2')"
$1 -m timeit -s 'import dateutil.parser' "dateutil.parser.parse('$2')"
$1 -m timeit -s 'import aniso8601' "aniso8601.parse_datetime('$2')"
$1 -m timeit -s 'import iso8601' "iso8601.parse_date('$2')"
$1 -m timeit -s 'import isodate' "isodate.parse_datetime('$2')"
$1 -m timeit -s 'import arrow' "arrow.get('$2').datetime"
$1 -m timeit -s 'import pendulum' "pendulum.parse('$2')"
$1 -m timeit -s 'import maya' "maya.parse('$2')"
$1 -m timeit -s 'import udatetime' "udatetime.from_string('$2')"
$1 -m timeit -s 'from iso8601utils import parsers' "parsers.datetime('$2')"
$1 -m timeit -s 'import PySO8601' "PySO8601.parse('$2')"
$1 -m timeit -s 'import moment' "moment.date('$2')"
$1 -m timeit -s 'from str2date import str2date' "str2date('$2')"
```

**Execution:**
`./comparisons.sh env36/bin/python '2014-01-09T21:48:00-05:30'`

**Comment by movermeyer** [comment]
I'll probably rework it to by a Python script instead, and then have `tox` be able to run it for each interpreter.

Then we'll be able to check in a reuseable script to do the benchmarks for future releases. 
(It might even be able to format it into reStructuredText tables for easy copy-paste into the README.)

**Comment by movermeyer** [comment]
Also, fun fact: the person who wrote `udatetime` [published a benchmark](https://aboutsimon.com/blog/2016/08/11/ciso8601-vs-mxDateTime-vs-udatetime.html) a while back that made ciso8601 look slower.

They never showed their test code, nor the versions they used, but my tests show us beating udatetime by the same margins. :stuck_out_tongue:

**Comment by visch** [comment]
Was going to use pendulum as I already had the dependency added, and your amazing benchmark section in the README said pendulum was also pretty fast.

It's not anymore since 2.0 due to C Extensions not being added

https://pendulum.eustace.io/blog/the-road-to-pendulum-2-0.html 

Just a bump on getting the benchmarks updated :D

**Comment by movermeyer** [comment]
> pendulum was also pretty fast.

@visch Pendulum is also pretty fast. The benchmarks are currently using pendulum 2.1.2, which is the latest release.

🤔😕🤔 

> due to C Extensions not being added

That link says that the C extensions were only not being added for Python 2.7, which matches what we see in the benchmarks table:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/1459385/145600847-b7ede92c-0c4e-4669-a7bf-ddfd9b75e14d.png">

(If you're still on Python 2.7, you're going to have a bad time as more and more of the ecosystem moves on. `ciso8601` itself might drop it in a future release. 😬)

---

Thanks for pinging me on this issue. The benchmarks were actually recently updated (2021-11-14), so this issue can be closed.

**Comment by visch** [comment]
> > pendulum was also pretty fast.
> 
> @visch Pendulum is also pretty fast. The benchmarks are currently using pendulum 2.1.2, which is the latest release.
> 
> 🤔😕🤔
> 
> > due to C Extensions not being added
> 
> That link says that the C extensions were only not being added for Python 2.7, which matches what we see in the benchmarks table:
> 
> <img alt="image" width="718" src="https://user-images.githubusercontent.com/1459385/145600847-b7ede92c-0c4e-4669-a7bf-ddfd9b75e14d.png">
> 
> (If you're still on Python 2.7, you're going to have a bad time as more and more of the ecosystem moves on. `ciso8601` itself might drop it in a future release. 😬)
> 
> Thanks for pinging me on this issue. The benchmarks were actually recently updated (2021-11-14), so this issue can be closed.

Yeah I'm not on 2.7, currently using 3.8. I'll have to put a scenario together I guess!

**Comment by movermeyer** [comment]
@visch You can see the code we use for running the benchmark [here](https://github.com/closeio/ciso8601/blob/20420c2e7eba6760337ea6f36a26876b4da94bba/benchmarking/perform_comparison.py#L26), or see the [benchmarking README](https://github.com/closeio/ciso8601/blob/master/benchmarking/README.rst) is you want to run it yourself.
