### ISSUE TITLE
20140203 04:05:.123456 shouldn't parse fractional seconds

### ISSUE THREAD

**Issue by aJanuary** [closeio/ciso8601#6]
A missing seconds fragment between two time separators should cause it to stop parsing and consider the rest of the string junk, but instead it treats seconds as zero.

Test:

ciso8601.parse_datetime('20140203 04:05:.123456')

Expected:

datetime.datetime(2014, 2, 3, 4, 5)

Actual:

datetime.datetime(2014, 2, 3, 4, 5, 0, 123456)

**Comment by thomasst** [comment]
Thanks for reporting this. Right now the library returns `None` for some (but not all) invalid input. PRs are welcome :)

**Comment by thomasst** [comment]
Per https://github.com/closeio/ciso8601/issues/26 we should just return `None` in this case.

**Comment by thomasst** [comment]
Fixed in https://github.com/closeio/ciso8601/pull/31

**Comment by movermeyer** [comment]
Fixed in version `2.0.0` (#43).

Attempting to parse this out-of-spec timestamp now raises a `ValueError`.
