### ISSUE TITLE
Add datetime.fromisoformat to the benchmarks

### ISSUE THREAD

**Issue by Morwenn** [closeio/ciso8601#66]
Python 3.7 added [`datetime.fromisoformat`][1] to the datetime library, which might be another target to add to the benchmarks without timezones for completeness.

Now a few remarks about the function:
* It is only meant to parse the result of `isoformat`, so it isn't super flexible compared to what you provide
* I looked at the implementation and while it should be faster than using the equivalent `strptime`, it is still implemented in pure Python, so it's highly unlikely to beat your implementation.

  [1]: https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat

**Comment by movermeyer** [comment]
Thanks! Yes, I've been looking into `datetime.fromisoformat` intensely.

In cPython, it is actually implemented [both in Python](https://github.com/python/cpython/blob/08c1da71030e0d6019b3493e0ffaf060a6aa5d8e/Lib/datetime.py#L1628) and [in C](https://github.com/python/cpython/blob/08c1da71030e0d6019b3493e0ffaf060a6aa5d8e/Modules/_datetimemodule.c#L4828) and the C version is faster than any other method (including `ciso8601`).
I've been working on a [backport of it to older Python versions](https://github.com/movermeyer/backports.datetime_fromisoformat/). 

There [is an open issue](https://github.com/closeio/ciso8601/issues/64) to rewrite the docs to be more comprehensive and inclusive of alternatives.

**Comment by Morwenn** [comment]
I wasn't aware that there was also a C implementation, it's nice to know :)
