### ISSUE TITLE
__version__ attribute just reads "CISO8601_VERSION"

### ISSUE THREAD

**Issue by ianhoffman** [closeio/ciso8601#80]
Thanks for the great work on this library. I just upgraded some dateparsing code to use it and saw massive performance gains. I also noticed a minor bug -- the ciso_8601 module isn't correctly setting the "__version__" attribute:

```
# encoding: utf-8
# module ciso8601
# from /opt/pyre/lib/python3.5/site-packages/ciso8601.cpython-35m-x86_64-linux-gnu.so
# by generator 1.145
# no doc
# no imports

# Variables with simple values

__version__ = 'CISO8601_VERSION'

# functions

def parse_datetime(*args, **kwargs): # real signature unknown
    """ Parse a ISO8601 date time string. """
    pass

def parse_datetime_as_naive(*args, **kwargs): # real signature unknown
    """ Parse a ISO8601 date time string, ignoring the time zone component. """
    pass

def parse_rfc3339(*args, **kwargs): # real signature unknown
    """ Parse an RFC 3339 date time string. """
    pass

# no classes
# variables with complex values

__loader__ = None # (!) real value is ''

__spec__ = None # (!) real value is ''
```

I expect `__version__` should equal `2.1.1`, not `CISO8601_VERSION`. I peeked a bit into the C code and noticed this is set from there, using a macro defined in setup.py... I don't have much experience building python modules from C, but I'm happy to look into this if ya'll are jammed.

Thanks again for the great work.

**Comment by movermeyer** [comment]
Thanks for this issue. Indeed, this is a bug. 🐞 

The `__version__` attribute implementation is relatively new in `ciso8601`. It was added in https://github.com/closeio/ciso8601/pull/60

If you're up for it, I'd love to see a PR for this. Otherwise, I'll get around to it "sometime".

**Comment by ianhoffman** [comment]
Thanks @movermeyer . I'll give it a shot when I have some time -- likely this weekend or the next.

**Comment by ianhoffman** [comment]
[Turns out I had time for it tonight.](https://github.com/closeio/ciso8601/pull/81)
