### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by olliemath** [closeio/ciso8601#87]
Thanks for fixing https://github.com/closeio/ciso8601/pull/85 in https://github.com/closeio/ciso8601/commit/f21596ee5b6fc24ab6e6809db388a7b03c3e6d74 would you be able to do a release which includes the fix?

Currently we're downloading this dependency from git, rather than pypi, which is not ideal.

**Comment by movermeyer** [comment]
The release is sitting, ready in #86 

Unfortunately, while I'm a maintainer, I don't have permissions to release to PyPI.

So we're waiting on @thomasst, who has been very busy recently.

**Comment by thomasst** [comment]
Sorry for the delay! Should be released now.

**Comment by olliemath** [comment]
Thanks!
