### ISSUE TITLE
Failed building wheel for ciso8601 Ubuntu 18.04

### ISSUE THREAD

**Issue by v4l3nt1n** [closeio/ciso8601#88]
Hi Guys,

I'm having a hard time trying to install ciso8601==2.1.3
I already installed the wheel package (saw it on another issue).
Can you suggest a way to get it right?

Ubuntu 18.04
python 3.6.9
pip 9.0.1

Full Output
--

(venv) v4l3nt1n@v4l3nt1n-nb:~/_work/_dev/_dw/_dev/process-machine-project$ **pip install ciso8601**
Collecting ciso8601
  Using cached https://files.pythonhosted.org/packages/2c/da/626910cf8aca7ed2d5b34355eee8aeaaeb6ddd4e16f98d00a9e2ddad3a08/ciso8601-2.1.3.tar.gz
Building wheels for collected packages: ciso8601
  Running setup.py bdist_wheel for ciso8601 ... error
  Complete output from command /home/v4l3nt1n/_work/_dev/_dw/_dev/process-machine-project/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-j0oq0ixx/ciso8601/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpbfg9puakpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  package init file 'ciso8601/__init__.py' not found (or not a regular file)
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/ciso8601
  copying ciso8601/__init__.pyi -> build/lib.linux-x86_64-3.6/ciso8601
  copying ciso8601/py.typed -> build/lib.linux-x86_64-3.6/ciso8601
  running build_ext
  building 'ciso8601' extension
  creating build/temp.linux-x86_64-3.6
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DCISO8601_VERSION=2.1.3 -I/home/v4l3nt1n/_work/_dev/_dw/_dev/process-machine-project/venv/include -I/usr/include/python3.6m -c module.c -o build/temp.linux-x86_64-3.6/module.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ciso8601
  Running setup.py clean for ciso8601
Failed to build ciso8601
Installing collected packages: ciso8601
  Running setup.py install for ciso8601 ... error
    Complete output from command /home/v4l3nt1n/_work/_dev/_dw/_dev/process-machine-project/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-j0oq0ixx/ciso8601/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7xs_tlks-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/v4l3nt1n/_work/_dev/_dw/_dev/process-machine-project/venv/include/site/python3.6/ciso8601:
    running install
    running build
    running build_py
    package init file 'ciso8601/__init__.py' not found (or not a regular file)
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ciso8601
    copying ciso8601/__init__.pyi -> build/lib.linux-x86_64-3.6/ciso8601
    copying ciso8601/py.typed -> build/lib.linux-x86_64-3.6/ciso8601
    running build_ext
    building 'ciso8601' extension
    creating build/temp.linux-x86_64-3.6
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DCISO8601_VERSION=2.1.3 -I/home/v4l3nt1n/_work/_dev/_dw/_dev/process-machine-project/venv/include -I/usr/include/python3.6m -c module.c -o build/temp.linux-x86_64-3.6/module.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/v4l3nt1n/_work/_dev/_dw/_dev/process-machine-project/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-j0oq0ixx/ciso8601/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7xs_tlks-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/v4l3nt1n/_work/_dev/_dw/_dev/process-machine-project/venv/include/site/python3.6/ciso8601" failed with error code 1 in /tmp/pip-build-j0oq0ixx/ciso8601/

Thank you very much for this lib and work!!

**Comment by v4l3nt1n** [comment]
I kept trying different things and i finally got it.
Its very important to have all python-dev packages up to date when working virtualenv

Run
sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y

Then create env:
python3.6 -m venv venv

Then install wheel package or add to requirements.txt
pip3 install wheel

Finally
(venv) pip install ciso8601


Thanks.

**Comment by doobran** [comment]
> I kept trying different things and i finally got it. Its very important to have all python-dev packages up to date when working virtualenv
> 
> Run sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
> 
> Then create env: python3.6 -m venv venv
> 
> Then install wheel package or add to requirements.txt pip3 install wheel
> 
> Finally (venv) pip install ciso8601
> 
> Thanks.

Thank! Updating my venv with "sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y" worked wonders!
